Recycler view
dashsublett/MonsterFetch pull request #2
Opened 2019-01-21 20:40 UTC by dashsublett

2019-01-21 21:22 UTC, rudynewball requested changes

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +private class MainActivity : AppCompatActivity() {
remove `private`

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +    private val monsters: ArrayList<String> = ArrayList() // Data set for recycler view
`listOf()`
`private val monsters = mutableListOf<String>() // Data set for recycler view`

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +        this.rv_monster_list.adapter = MonsterAdapter(monsters, this)
`this.rvMonsterList` - rename in xml

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +        if (monsterIt != null)
add curly braces

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +                retList.add(monsterIt.next().name)
return `List<Monster>` instead

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +private class UpdateMonsterList(val monsterList: ArrayList<String>)
take a closure (callback) instead of a list.
`callback: ((listOfMonsters: List<Monster) -> Unit)`

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +        // Asynchronously retrieve list of monsters, parse into List, add to data set
Add loading circle

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MonsterAdapter.kt
> +class MonsterAdapter(val items: ArrayList<String>, val context: Context)
code to an interface `List<String>`

2019-01-21 21:22 UTC, rudynewball commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/rv_monster_list"
camelCase

2019-01-22 23:25 UTC, rudynewball requested changes

2019-01-22 23:25 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +        this.rvMonsterList.layoutManager = LinearLayoutManager(this)
Why are you setting the layout manager?

2019-01-22 23:25 UTC, rudynewball commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +private class UpdateMonsterList(private val adapterRef: MonsterAdapter,
Should only have one parameter which is a callback method that has a `List<Monster>` as it's parameter.
```
private class UpdateMonsterList(private val callback: ((List<Monster>) -> Unit) : AsyncTask<Unit, Unit, List<Monster>>() {}
```

2019-01-23 14:41 UTC, dashsublett commented on app/src/main/java/com/example/dsublett/monsterfetch/MainActivity.kt
> +        this.rvMonsterList.layoutManager = LinearLayoutManager(this)
When I was creating the RecyclerView, I was following [this documentation](https://developer.android.com/guide/topics/ui/layout/recyclerview), which says:

>Once you have added a RecyclerView widget to your layout, obtain a handle to the object, connect it to a layout manager, and attach an adapter for the data to be displayed...

Also if I comment out that line, the monster list does not get displayed.

2019-01-23 17:52 UTC, rudynewball approved these changes

2019-01-23 17:53 UTC, merged